
-- create the family table
CREATE TABLE family (
    family_id INT GENERATED BY DEFAULT AS IDENTITY,
    family_name VARCHAR(60) NOT NULL,
    PRIMARY KEY (family_id)
);

-- create the customer table
CREATE TABLE customer (
  customer_id INT GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR(25) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  username VARCHAR(30) UNIQUE NOT NULL,
  email VARCHAR(40),
  passhash VARCHAR(150),
  created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT true,
  last_login TIMESTAMP DEFAULT NULL,
  family_id INT NOT NULL,
  PRIMARY KEY (customer_id),
  FOREIGN KEY (family_id) REFERENCES family(family_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- create the goal_type table
CREATE TABLE goal_type (
    goal_type_id INT GENERATED BY DEFAULT AS IDENTITY,
    goal_type_description VARCHAR(50) NOT NULL,
    PRIMARY KEY (goal_type_id)
);

-- create the goal table
CREATE TABLE goal (
    goal_id INT GENERATED BY DEFAULT AS IDENTITY,
    goal_description VARCHAR(200) NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    goal_type_id INT NOT NULL,
    family_id INT NOT NULL,
    created_by INT NOT NULL,
    PRIMARY KEY (goal_id),
    FOREIGN KEY (goal_type_id) REFERENCES goal_type(goal_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (family_id) REFERENCES family(family_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (created_by) REFERENCES customer(customer_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- create the task table
CREATE TABLE task (
    task_id INT GENERATED BY DEFAULT AS IDENTITY,
    task_description VARCHAR(200) NOT NULL,
    is_active BOOLEAN DEFAULT true,
    is_completed BOOLEAN DEFAULT false,
    due_date TIMESTAMP,
    completion_date TIMESTAMP DEFAULT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    family_id INT NOT NULL,
    created_by INT NOT NULL,
    assigned_to INT DEFAULT NULL,
    PRIMARY KEY (task_id),
    FOREIGN KEY (family_id) REFERENCES family(family_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (created_by) REFERENCES customer(customer_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (assigned_to) REFERENCES customer(customer_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

--create the activity table
CREATE TABLE activity (
    activity_id INT GENERATED BY DEFAULT AS IDENTITY,
    activity_description VARCHAR(200) NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    from_date TIMESTAMP NOT NULL,
    to_date TIMESTAMP NOT NULL,
    family_id INT NOT NULL,
    created_by INT NOT NULL,
    PRIMARY KEY (activity_id),
    FOREIGN KEY (family_id) REFERENCES family(family_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (created_by) REFERENCES customer(customer_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- create the priority table
CREATE TABLE Priority (
    priority_id INT GENERATED BY DEFAULT AS IDENTITY,
    priority_description VARCHAR(50) NOT NULL,
    weight INT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    family_id INT NOT NULL,
    created_by INT NOT NULL,
    PRIMARY KEY (priority_id),
    FOREIGN KEY (family_id) REFERENCES family(family_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (created_by) REFERENCES customer(customer_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);